# Reference: https://github.com/i3/i3/blob/next/etc/config

# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

on-focus-changed = ['move-mouse window-lazy-center'] # Mouse lazily follows any focus (window or workspace)

after-startup-command = [
  'exec-and-forget borders active_color=0xff00ffff inactive_color=0xffff00ff width=8.0'
]

[workspace-to-monitor-force-assignment]
    main = '^C49HG9.*' 
    right = '^Built.*'                            # Monitor sequence number from left to right. 1-based indexing
    top = '^ASUS.*' 

[[on-window-detected]]
    if.app-name-regex-substring = 'kitty'
    if.window-title-regex-substring = 'KittyPopup'
    run = ['layout floating']

[[on-window-detected]]
    if.app-name-regex-substring = 'DeskPad'
    run = ['layout floating']

[mode.main.binding]
    ctrl-shift-enter = '''exec-and-forget osascript -e '
    do shell script "open -na /Applications/Google\\ Chrome.app --args --profile-directory=\"Profile 1\" --new-window"'
    '''
    shift-alt-enter = '''exec-and-forget osascript -e '
    do shell script "open -na /Applications/Google\\ Chrome.app --args --profile-directory=\"Profile 2\" --new-window"'
    '''
    cmd-enter = 'exec-and-forget TMUX= && open -na ghostty'
    cmd-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors left'
    cmd-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors down'
    cmd-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors up'
    cmd-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action wrap-around-all-monitors right'
    cmd-ctrl-h = 'move left'
    cmd-ctrl-j = 'move down'
    cmd-ctrl-k = 'move up'
    cmd-ctrl-l = 'move right'
    cmd-shift-h = 'exec-and-forget move-window left'
    cmd-shift-j = 'exec-and-forget move-window down'
    cmd-shift-k = 'exec-and-forget move-window up'
    cmd-shift-l = 'exec-and-forget move-window right'
    alt-f = 'fullscreen'
    alt-t = 'layout tiling'
    alt-s = 'layout v_accordion'
    alt-w = 'layout h_accordion'
    alt-e = 'layout tiles horizontal vertical'
    alt-shift-space = 'layout floating tiling'
    cmd-shift-c = 'exec-and-forget ao new'
    cmd-shift-n = 'exec-and-forget ao next'
    cmd-shift-r = 'exec-and-forget ao prev'
    alt-shift-r = 'reload-config'
    alt-r = 'mode resize'
    cmd-1 = 'exec-and-forget ao jump 1'
    cmd-2 = 'exec-and-forget ao jump 2'
    cmd-3 = 'exec-and-forget ao jump 3'
    cmd-4 = 'exec-and-forget ao jump 4'
    cmd-5 = 'exec-and-forget ao jump 5'
    cmd-6 = 'exec-and-forget ao jump 6'
    cmd-7 = 'exec-and-forget ao jump 7'
    cmd-8 = 'exec-and-forget ao jump 8'
    cmd-9 = 'exec-and-forget ao jump 9'
    cmd-t = 'exec-and-forget ao add'
    cmd-u = 'exec-and-forget ao edit'
    cmd-m = 'exec-and-forget ao mouse'
    alt-tab = 'exec-and-forget ao cycle next'
    alt-shift-tab = 'exec-and-forget ao cycle prev'

[mode.resize.binding]
    h = 'resize width -50'
    j = 'resize height +50'
    k = 'resize height -50'
    l = 'resize width +50'
    enter = 'mode main'
    esc = 'mode main'

[gaps]
inner.horizontal = 10
inner.vertical   = 10
outer.left       = 10
outer.bottom     = 10
outer.top        = 10
outer.right      = 10
